// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.3
// source: model/music.proto

package pbfiles

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 音乐类型
type Type int32

const (
	Type_Classical Type = 0 // 古典
	Type_Popular   Type = 1 // 流行
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "Classical",
		1: "Popular",
	}
	Type_value = map[string]int32{
		"Classical": 0,
		"Popular":   1,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_model_music_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_model_music_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_model_music_proto_rawDescGZIP(), []int{0}
}

// 音乐
type Music struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                     // id
	Type   Type    `protobuf:"varint,2,opt,name=type,proto3,enum=model.Type" json:"type,omitempty"` // 类型
	Name   string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                  // 名字
	Price  float32 `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`              // 价格
	Author string  `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`              // 作者
}

func (x *Music) Reset() {
	*x = Music{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_music_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Music) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Music) ProtoMessage() {}

func (x *Music) ProtoReflect() protoreflect.Message {
	mi := &file_model_music_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Music.ProtoReflect.Descriptor instead.
func (*Music) Descriptor() ([]byte, []int) {
	return file_model_music_proto_rawDescGZIP(), []int{0}
}

func (x *Music) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Music) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_Classical
}

func (x *Music) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Music) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Music) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

var File_model_music_proto protoreflect.FileDescriptor

var file_model_music_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x7a, 0x0a, 0x05, 0x4d, 0x75,
	0x73, 0x69, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x2a, 0x22, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d,
	0x0a, 0x09, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x10, 0x01, 0x42, 0x0e, 0x5a, 0x0c, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x70, 0x62, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_model_music_proto_rawDescOnce sync.Once
	file_model_music_proto_rawDescData = file_model_music_proto_rawDesc
)

func file_model_music_proto_rawDescGZIP() []byte {
	file_model_music_proto_rawDescOnce.Do(func() {
		file_model_music_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_music_proto_rawDescData)
	})
	return file_model_music_proto_rawDescData
}

var file_model_music_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_model_music_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_music_proto_goTypes = []interface{}{
	(Type)(0),     // 0: model.Type
	(*Music)(nil), // 1: model.Music
}
var file_model_music_proto_depIdxs = []int32{
	0, // 0: model.Music.type:type_name -> model.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_model_music_proto_init() }
func file_model_music_proto_init() {
	if File_model_music_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_model_music_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Music); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_music_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_music_proto_goTypes,
		DependencyIndexes: file_model_music_proto_depIdxs,
		EnumInfos:         file_model_music_proto_enumTypes,
		MessageInfos:      file_model_music_proto_msgTypes,
	}.Build()
	File_model_music_proto = out.File
	file_model_music_proto_rawDesc = nil
	file_model_music_proto_goTypes = nil
	file_model_music_proto_depIdxs = nil
}
